<template> <!-- Generated by Codex (design provided) -->
  <div class="auth-bg">
    <div class="card" role="main" aria-label="Register">
      <div class="logo" aria-hidden="true">
        <!-- simple book icon (replace with your asset if you have one) -->
        <svg width="44" height="44" viewBox="0 0 24 24" fill="none">
          <path
            d="M4 19.5V6.6c0-.9.7-1.6 1.6-1.6H11c1 0 1.9.4 2.5 1.1.6-.7 1.5-1.1 2.5-1.1h5.4c.9 0 1.6.7 1.6 1.6V19.5c0 .6-.5 1-1.1.9-1.8-.4-4.2-.9-5.9-.9-1.9 0-3.2.4-4.5 1.1-1.3-.7-2.6-1.1-4.5-1.1-1.7 0-4.1.5-5.9.9-.6.1-1.1-.3-1.1-.9Z"
            stroke="currentColor"
            stroke-width="1.6"
            stroke-linejoin="round"
          />
          <path d="M12 6.4V20.6" stroke="currentColor" stroke-width="1.6" />
        </svg>
      </div>

      <h1 class="title">Join CourseHub</h1>
      <p class="subtitle">Create your account to get started</p>

      <form class="form" @submit.prevent="onSubmit">
        <div class="field">
          <label class="label" for="name">Full Name</label>
          <input
            id="name"
            class="input"
            v-model.trim="form.name"
            type="text"
            autocomplete="name"
            placeholder="John Doe"
            required
          />
        </div>

        <div class="field">
          <label class="label" for="email">Email</label>
          <input
            id="email"
            class="input"
            v-model.trim="form.email"
            type="email"
            autocomplete="email"
            placeholder="you@example.com"
            required
          />
        </div>

        <div class="field">
          <label class="label" for="password">Password</label>
          <input
            id="password"
            class="input"
            v-model="form.password"
            type="password"
            autocomplete="new-password"
            placeholder="••••••••"
            minlength="8"
            required
          />
          <p class="hint">Minimum 8 characters.</p>
        </div>

        <div class="field">
          <label class="label" for="password">Confirm Password</label>
          <input
            id="password"
            class="input"
            v-model="form.confirmPassword"
            type="password"
            autocomplete="new-password"
            placeholder="••••••••"
            minlength="8"
            required
          />
          <p class="hint">Re-enter your password.</p>
        </div>

        <div class="field">
          <div class="label">I am a</div>
          <div class="roleRow" role="radiogroup" aria-label="Role">
            <button
              type="button"
              class="roleBtn"
              :class="{ active: form.role === 'STUDENT' }"
              @click="form.role = 'STUDENT'"
              role="radio"
              :aria-checked="form.role === 'STUDENT'"
            >
              Student
            </button>
            <button
              type="button"
              class="roleBtn"
              :class="{ active: form.role === 'PROFESSOR' }"
              @click="form.role = 'PROFESSOR'"
              role="radio"
              :aria-checked="form.role === 'PROFESSOR'"
            >
              Professor
            </button>
          </div>
        </div>

        <p v-if="error" class="error" role="alert">{{ error }}</p>

        <button class="primary" type="submit" :disabled="loading">
          <span class="btnIcon" aria-hidden="true">
            <!-- user+ icon -->
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
              <path d="M15 21a6 6 0 0 0-12 0" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>
              <path d="M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z" stroke="currentColor" stroke-width="1.8"/>
              <path d="M19 8v6" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>
              <path d="M16 11h6" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>
            </svg>
          </span>
          {{ loading ? "Creating..." : "Create Account" }}
        </button>

        <div class="footer">
          <span>Already have an account?</span>
          <a class="link" href="/login">Sign in</a>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { reactive, ref } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();
const loading = ref(false);
const error = ref("");

const form = reactive({
  name: "",
  email: "",
  password: "",
  confirmPassword: "",
  role: "STUDENT", // default matches your screenshot
});

function validate() {
  if (!form.name) return "Full name is required.";
  if (!form.email) return "Email is required.";
  if (!form.password || form.password.length < 8) return "Password must be at least 8 characters.";
  if(form.password !== form.confirmPassword) return "Passwords do not match.";
  if (!form.role) return "Role is required.";
  return "";
}

async function onSubmit() {
  error.value = validate();
  if (error.value) return;

  loading.value = true;
  try {
    const response = await fetch("/api/auth/register", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name: form.name,
        email: form.email,
        password: form.password,
        role: form.role,
      }),
    });

    if (!response.ok) {
      if (response.status === 409) error.value = "Email already in use.";
      else if (response.status === 400) error.value = "Invalid input. Please check your fields.";
      else error.value = "Registration failed. Try again.";
      return;
    }

    // change if your app uses a different landing route
    router.push("/dashboard");
  } catch (_e) {
    error.value = "Registration failed. Try again.";
  } finally {
    loading.value = false;
  }
}
</script>

<style scoped>
.auth-bg{
  min-height:100vh;
  display:flex;
  align-items:center;
  justify-content:center;
  padding:32px 16px;
  background:
    radial-gradient(1200px 600px at 50% 0%, rgba(84, 120, 255, .18), rgba(255,255,255,0) 60%),
    radial-gradient(900px 500px at 10% 30%, rgba(120, 200, 255, .14), rgba(255,255,255,0) 55%),
    linear-gradient(180deg, #f3f7ff, #eef3ff);
}

.card{
  width: min(520px, 92vw);
  background:#fff;
  border-radius:18px;
  box-shadow: 0 18px 45px rgba(16, 24, 40, .12);
  padding:32px 34px 24px;
  border: 1px solid rgba(0,0,0,.06);
}

.logo{
  display:flex;
  justify-content:center;
  margin-bottom:10px;
  color:#4f46e5;
}

.title{
  text-align:center;
  font-size:20px;
  font-weight:700;
  margin:0;
  color:#111827;
}

.subtitle{
  text-align:center;
  margin:6px 0 22px;
  color:#6b7280;
  font-size:14px;
}

.form{ display:flex; flex-direction:column; gap:16px; }

.field{ display:flex; flex-direction:column; gap:8px; }

.label{
  font-size:13px;
  font-weight:600;
  color:#111827;
}

.input{
  height:44px;
  border-radius:10px;
  border:1px solid #d6dbe6;
  padding:0 14px;
  font-size:14px;
  outline:none;
  transition: box-shadow .15s, border-color .15s;
}

.input:focus{
  border-color:#4f46e5;
  box-shadow: 0 0 0 4px rgba(79, 70, 229, .12);
}

.hint{
  margin:0;
  font-size:12px;
  color:#6b7280;
}

.roleRow{
  display:grid;
  grid-template-columns: 1fr 1fr;
  gap:14px;
}

.roleBtn{
  height:46px;
  border-radius:12px;
  border:2px solid #e5e7eb;
  background:#fff;
  font-weight:600;
  cursor:pointer;
  transition: transform .05s, border-color .15s, background .15s, box-shadow .15s, color .15s;
  color:#111827;
}

.roleBtn:active{ transform: scale(.99); }

.roleBtn.active{
  border-color:#4f46e5;
  background: rgba(79, 70, 229, .08);
  box-shadow: 0 0 0 4px rgba(79, 70, 229, .10);
  color:#4f46e5;
}

.primary{
  margin-top:4px;
  height:48px;
  border:none;
  border-radius:12px;
  background:#4f46e5;
  color:white;
  font-weight:700;
  cursor:pointer;
  display:flex;
  align-items:center;
  justify-content:center;
  gap:10px;
  transition: filter .15s, transform .05s;
}

.primary:hover{ filter: brightness(0.98); }
.primary:active{ transform: scale(.99); }
.primary:disabled{
  opacity:.7;
  cursor:not-allowed;
}

.btnIcon{
  display:inline-flex;
  align-items:center;
  justify-content:center;
}

.error{
  margin:0;
  color:#b42318;
  background:#fff1f0;
  border:1px solid #ffccc7;
  padding:10px 12px;
  border-radius:10px;
  font-size:13px;
}

.footer{
  display:flex;
  justify-content:center;
  gap:6px;
  margin-top:10px;
  font-size:14px;
  color:#6b7280;
}

.link{
  color:#4f46e5;
  font-weight:700;
  text-decoration:none;
}

.link:hover{ text-decoration:underline; }
</style>
